PATHO_GENES = {"Oncology": [
    {"symbol": "TP53", "name": "Tumor protein p53"},
    {"symbol": "BRCA1", "name": "Breast cancer type 1 susceptibility protein"},
    {"symbol": "BRCA2", "name": "Breast cancer type 2 susceptibility protein"},
    {"symbol": "KRAS", "name": "GTPase KRas"},
    {"symbol": "NRAS", "name": "GTPase NRas"},
    {"symbol": "HRAS", "name": "GTPase HRas"},
    {"symbol": "BRAF", "name": "Serine/threonine-protein kinase B-raf"},
    {"symbol": "EGFR", "name": "Epidermal growth factor receptor"},
    {"symbol": "PIK3CA", "name": "Phosphatidylinositol 4,5-bisphosphate 3-kinase catalytic subunit alpha"},
    {"symbol": "ALK", "name": "Anaplastic lymphoma kinase"},
    {"symbol": "MET", "name": "Hepatocyte growth factor receptor"},
    {"symbol": "ERBB2", "name": "Receptor tyrosine-protein kinase erbB-2 (HER2)"},
    {"symbol": "PTEN", "name": "Phosphatase and tensin homolog"},
    {"symbol": "CDKN2A", "name": "Cyclin-dependent kinase inhibitor 2A"},
    {"symbol": "APC", "name": "Adenomatous polyposis coli protein"},
    {"symbol": "MLH1", "name": "MutL homolog 1"},
    {"symbol": "MSH2", "name": "MutS homolog 2"},
    {"symbol": "RB1", "name": "Retinoblastoma-associated protein"},
    {"symbol": "VHL", "name": "Von Hippel-Lindau tumor suppressor"},
    {"symbol": "STK11", "name": "Serine/threonine kinase 11 (LKB1)"},
    {"symbol": "NPM1", "name": "Nucleophosmin (acute myeloid leukemia)"},
    {"symbol": "FLT3", "name": "FMS-like tyrosine kinase 3"},
    {"symbol": "IDH1", "name": "Isocitrate dehydrogenase 1"},
    {"symbol": "IDH2", "name": "Isocitrate dehydrogenase 2"},
], "Rare Diseases": [
    {"symbol": "CFTR", "name": "Cystic fibrosis transmembrane conductance regulator"},
    {"symbol": "SMN1", "name": "Survival of motor neuron protein 1"},
    {"symbol": "FBN1", "name": "Fibrillin-1"},
    {"symbol": "GAA", "name": "Acid alpha-glucosidase"},
    {"symbol": "DMD", "name": "Dystrophin"},
    {"symbol": "PAH", "name": "Phenylalanine-4-hydroxylase"},
    {"symbol": "IDUA", "name": "Alpha-L-iduronidase"},
    {"symbol": "GBA", "name": "Glucocerebrosidase"},
    {"symbol": "COL7A1", "name": "Collagen alpha-1(VII) chain"},
    {"symbol": "PHEX", "name": "Phosphate-regulating neutral endopeptidase"},
    {"symbol": "MECP2", "name": "Methyl CpG binding protein 2"},
    {"symbol": "GLA", "name": "Alpha-galactosidase A"},
    {"symbol": "LAMP2", "name": "Lysosome-associated membrane glycoprotein 2"},
    {"symbol": "SLC6A8", "name": "Creatine transporter 1"},
    {"symbol": "TTR", "name": "Transthyretin (familial amyloidosis)"},
    {"symbol": "PMP22", "name": "Peripheral myelin protein 22 (Charcot-Marie-Tooth)"},
], "Cardiology": [
    {"symbol": "MYH7", "name": "Myosin-7"},
    {"symbol": "SCN5A", "name": "Sodium channel protein type 5 subunit alpha"},
    {"symbol": "TNNT2", "name": "Troponin T, cardiac muscle"},
    {"symbol": "LMNA", "name": "Prelamin-A/C"},
    {"symbol": "RYR2", "name": "Ryanodine receptor 2"},
    {"symbol": "KCNQ1", "name": "Potassium voltage-gated channel subfamily Q member 1"},
    {"symbol": "MYBPC3", "name": "Myosin-binding protein C, cardiac-type"},
    {"symbol": "PCSK9", "name": "Proprotein convertase subtilisin/kexin type 9"},
    {"symbol": "LDLR", "name": "Low-density lipoprotein receptor"},
    {"symbol": "TTN", "name": "Titin (dilated cardiomyopathy)"},
], "Neurology": [
    {"symbol": "APP", "name": "Amyloid-beta A4 protein precursor"},
    {"symbol": "PSEN1", "name": "Presenilin-1"},
    {"symbol": "MAPT", "name": "Microtubule-associated protein tau"},
    {"symbol": "HTT", "name": "Huntingtin"},
    {"symbol": "SOD1", "name": "Superoxide dismutase [Cu-Zn]"},
    {"symbol": "LRRK2", "name": "Leucine-rich repeat serine/threonine-protein kinase 2"},
    {"symbol": "SNCA", "name": "Alpha-synuclein"},
    {"symbol": "GRN", "name": "Progranulin"},
    {"symbol": "TARDBP", "name": "TAR DNA-binding protein 43"},
    {"symbol": "C9orf72", "name": "Chromosome 9 open reading frame 72 (ALS/FTD)"},
], "Immunology": [
    {"symbol": "HLA-A", "name": "Major histocompatibility complex, class I, A"},
    {"symbol": "IL2RA", "name": "Interleukin-2 receptor subunit alpha"},
    {"symbol": "CTLA4", "name": "Cytotoxic T-lymphocyte protein 4"},
    {"symbol": "FOXP3", "name": "Forkhead box protein P3"},
    {"symbol": "TNF", "name": "Tumor necrosis factor"},
    {"symbol": "IFNG", "name": "Interferon gamma"},
    {"symbol": "IL6", "name": "Interleukin-6"},
    {"symbol": "STAT3", "name": "Signal transducer and activator of transcription 3"},
    {"symbol": "JAK3", "name": "Janus kinase 3"},
    {"symbol": "IL10", "name": "Interleukin-10"},
], "Metabolism/Endocrinology": [
    {"symbol": "INS", "name": "Insulin"},
    {"symbol": "GCK", "name": "Glucokinase"},
    {"symbol": "GHR", "name": "Growth hormone receptor"},
    {"symbol": "LEP", "name": "Leptin"},
    {"symbol": "MC4R", "name": "Melanocortin receptor 4"},
    {"symbol": "TSHR", "name": "Thyroid-stimulating hormone receptor"},
    {"symbol": "POMC", "name": "Pro-opiomelanocortin"},
    {"symbol": "CYP21A2", "name": "Steroid 21-hydroxylase"},
    {"symbol": "HNF1A", "name": "Hepatocyte nuclear factor 1-alpha"},
    {"symbol": "PPARG", "name": "Peroxisome proliferator-activated receptor gamma"},
], "Infectious Diseases": [
    {"symbol": "CCR5", "name": "C-C chemokine receptor type 5 (HIV coreceptor)"},
    {"symbol": "TLR4", "name": "Toll-like receptor 4"},
    {"symbol": "IL28B", "name": "Interferon lambda-3 (HCV response)"},
    {"symbol": "CD4", "name": "T-cell surface glycoprotein CD4"},
    {"symbol": "IFNL3", "name": "Interferon lambda 3"},
    {"symbol": "DARC", "name": "Duffy antigen receptor for chemokines (malaria)"},
    {"symbol": "HLA-B", "name": "Major histocompatibility complex, class I, B"},
    {"symbol": "FUT2", "name": "Fucosyltransferase 2 (Norovirus resistance)"},
    {"symbol": "MX1", "name": "Interferon-induced GTP-binding protein Mx1"},
    {"symbol": "OAS1", "name": "2'-5'-oligoadenylate synthase 1"},
    {"symbol": "IFITM3", "name": "Interferon-induced transmembrane protein 3 (influenza severity)"},
], "Hematology": [
    {"symbol": "HBB", "name": "Hemoglobin subunit beta (sickle cell, thalassemia)"},
    {"symbol": "F8", "name": "Coagulation factor VIII"},
    {"symbol": "F9", "name": "Coagulation factor IX"},
    {"symbol": "VWF", "name": "Von Willebrand factor"},
    {"symbol": "G6PD", "name": "Glucose-6-phosphate dehydrogenase"},
    {"symbol": "HBA1", "name": "Hemoglobin subunit alpha 1"},
    {"symbol": "HBA2", "name": "Hemoglobin subunit alpha 2"},
    {"symbol": "ITGA2B", "name": "Integrin alpha-IIb"},
    {"symbol": "ITGB3", "name": "Integrin beta-3"},
    {"symbol": "ELANE", "name": "Neutrophil elastase"},
    {"symbol": "JAK2", "name": "Janus kinase 2 (myeloproliferative disorders)"},
], "Pharmacogenetics": [
    {"symbol": "CYP2D6", "name": "Cytochrome P450 2D6 (antidepressants, beta-blockers, opioids)"},
    {"symbol": "CYP2C9", "name": "Cytochrome P450 2C9 (warfarin, NSAIDs, antidiabetics)"},
    {"symbol": "CYP2C19", "name": "Cytochrome P450 2C19 (clopidogrel, proton pump inhibitors, antiepileptics)"},
    {"symbol": "CYP3A4", "name": "Cytochrome P450 3A4 (statins, immunosuppressants, anticancer drugs)"},
    {"symbol": "CYP3A5", "name": "Cytochrome P450 3A5 (tacrolimus, cyclosporine)"},
    {"symbol": "NAT2", "name": "N-acetyltransferase 2 (isoniazid, hydralazine, sulfonamides)"},
    {"symbol": "TPMT", "name": "Thiopurine S-methyltransferase (azathioprine, mercaptopurine, thioguanine)"},
    {"symbol": "NUDT15", "name": "Nudix hydrolase 15 (thiopurines, severe leukopenia)"},
    {"symbol": "VKORC1", "name": "Vitamin K epoxide reductase complex subunit 1 (warfarin)"},
    {"symbol": "SLCO1B1",
     "name": "Solute carrier organic anion transporter family member 1B1 (statins, myopathy risk)"},
    {"symbol": "DPYD", "name": "Dihydropyrimidine dehydrogenase (5-fluorouracil, capecitabine)"},
    {"symbol": "UGT1A1", "name": "UDP-glucuronosyltransferase 1A1 (irinotecan, hyperbilirubinemia risk)"},
    {"symbol": "G6PD", "name": "Glucose-6-phosphate dehydrogenase (primaquine, dapsone, sulfonamides)"},
], "Inflammation/Autoimmunity": [
    {"symbol": "HLA-DRB1",
     "name": "Major histocompatibility complex, class II, DR beta 1 (rheumatoid arthritis, multiple sclerosis)"},
    {"symbol": "PTPN22",
     "name": "Protein tyrosine phosphatase non-receptor type 22 (type 1 diabetes, rheumatoid arthritis)"},
    {"symbol": "IL23R", "name": "Interleukin-23 receptor (Crohn's disease, psoriasis, ankylosing spondylitis)"},
    {"symbol": "NOD2",
     "name": "Nucleotide-binding oligomerization domain-containing protein 2 (Crohn's disease, Blau syndrome)"},
    {"symbol": "STAT4",
     "name": "Signal transducer and activator of transcription 4 (systemic lupus erythematosus, rheumatoid arthritis)"},
    {"symbol": "TNFAIP3", "name": "TNF alpha-induced protein 3 (systemic lupus erythematosus, psoriasis)"},
    {"symbol": "IRF5", "name": "Interferon regulatory factor 5 (lupus, Sjögren's syndrome)"},
    {"symbol": "TYK2", "name": "Tyrosine kinase 2 (autoimmune susceptibility, multiple sclerosis)"},
    {"symbol": "CD40", "name": "CD40 molecule (autoimmune thyroid disease, rheumatoid arthritis)"},
    {"symbol": "CTLA4", "name": "Cytotoxic T-lymphocyte-associated protein 4 (autoimmunity, type 1 diabetes)"},
]}


